entities/global.ent

- replaced references to git.php.net
- removed the `url.git.php` macros. It seems that doesn't use anymore.

Replace references to git.php.net

---

.github/workflows/integrate.yaml

These are always failing, and as such it doesn't make much sense to try
to build them.

Disable builds of pl, ro and uk

---

scripts/qa/section-order.php

Since the reading of dotfiles files isn't something we're doing in this script, using the `FilesystemIterator::SKIP_DOTS` constant removes the use of the `isDot` check completely.  Also makes the code a bit easier to read IMHO.

Use FilesystemIterator constants instead of `isDot`

---

.gitignore
configure.php

See also php/phd#55 and php/web-php#434
The new `sources.xml` file contains the mapping from an XML ID to the source
XML file that declares it.
Generation of the `sources.xml` file is enabled by default. To disable it,
run `configure.php` with the `--disable-sources-file` option.
Example of `sources.xml` contents:
```xml
<?xml version="1.0"?>
<sources>
<item
id="extensions.membership"
lang="en"
path="appendices/extensions.xml"/>
<item
id="extensions.membership.core"
lang="en"
path="appendices/extensions.xml"/>
...
</sources>
```

Generate sources.xml

---

entities/global.ent

* GNU ftp page can be accessed via http
* SunSITE.unc.edu and MetaLab.unc.edu are now called "ibiblio."
https://en.wikipedia.org/wiki/Ibiblio
* openldap-stable only has an old version, so replace it with another page.
https://openldap.org/software/download/OpenLDAP/openldap-stable/

Replace the ftp:// URL with http as it is not easily accessible

---

configure.php

`nice php configure.php` assumes that the script was executed from the root of the project. `$_SERVER[SCRIPT_NAME]` will have the entire path to `configure.php`

Output entire file path

---

entities/global.ent

PHP manual has a few cases referring to PHP source code file, and
therefore add an external link entity to be used for this purpose.
Signed-off-by: Su, Tao <tao.su@intel.com>

Add a link entity for PHP source code reference

---

scripts/qa/section-order.php

Without this patch:
````
D:\git\php\phpdoc>php doc-base\scripts\qa\section-order.php
File D:\git\php\phpdoc/en/reference\filesystem/functions\delete.xml No parameters sections.
File D:\git\php\phpdoc/en/reference\filesystem/functions\delete.xml No returnvalues sections.
File D:\git\php\phpdoc/en/reference\misc/functions\die.xml No parameters sections.
File D:\git\php\phpdoc/en/reference\misc/functions\die.xml No returnvalues sections.
File D:\git\php\phpdoc/en/reference\oci8/oldaliases\ocifetchinto.xml No parameters sections.
File D:\git\php\phpdoc/en/reference\oci8/oldaliases\ocifetchinto.xml No returnvalues sections.
File D:\git\php\phpdoc/en/reference\parallel/functions\parallel.run.xml Invalid section role: 'scheduling-characteristics'.
File …
```

Properly skip SKIP_FILEs on Windows

---

entities/global.ent

https://researcher.watson.ibm.com/researcher/files/us-bacon/Bacon01Concurrent.pdf is now 404.
A new one is available at https://pages.cs.wisc.edu/~cymen/misc/interests/Bacon01Concurrent.pdf
A web archive version:
https://web.archive.org/web/20130525112405/https://researcher.watson.ibm.com/researcher/files/us-bacon/Bacon01Concurrent.pdf
--
Fix php/doc-ru#415

Fix url.gc-paper

---

entities/global.ent

This entity was removed on 18f17b8 due to being wrongly marked as obsolete in b2bc755. The reason for it being marked as obsolete may be due to a missing `&` character to reference the URL, introduced in https://github.com/php/doc-en/commit/f1e61c544919763580fbcaac3c618db3ccdde0dd

Add missing entity

---

.github/workflows/integrate.yaml

Hard-coding a certain php version doesn't make sense if we use ubuntu- *latest*.  Either we use the default php (as with this patch), or we commit to a certain Ubuntu version.
---
cc @mumumu, @localheinz

Use available php for GH CI

---

scripts/xml-check.php

The XML files in the docs are using 1 space for indentation, so setting the `XMLLINT_INDENT= ' '` environment variable and the `--format` option for `xmllint` ensuring the right indentation makes sense to me.
Regarding the encoding, [some files](https://github.com/php/doc-base/blob/140b2f686197c7100f5126a7e2ac16fb096ab309/funcindex.xml#L1) are using `UTF-8`, [others](https://github.com/php/doc-en/blob/cb010c77b6a2f0b35218cd1663cb8f5b88035069/reference/ibm_db2/configure.xml#L1) `utf-8`.
See: https://gnome.pages.gitlab.gnome.org/libxml2/xmllint.html

Update config for `xmllint` at `xml-check.php`

---

docbook/docbook-xml/docbook.dtd

As https://github.com/php/doc-en/commit/a6d209f4ff71ccba3f1255902827f5df3e092ff9 has been applied to all translations

Remove varentry modification from DTD

---

docbook/docbook-xml/docbook.dtd

This is a align the DTD more with standard DocBooks

Remove support for phd namespace attributes in DTD

---

entities/global.ent

Corrected the address to the documentation of the original package.

Fix wrong documentation url

---

configure.php

Fixes the issue with git ref printing on Windows showing the following error messages on each run:
```
The system cannot find the path specified.
The system cannot find the path specified.
The filename, directory name, or volume label syntax is incorrect.
doc-base:
The system cannot find the path specified.
The system cannot find the path specified.
The filename, directory name, or volume label syntax is incorrect.
en:
```
Additionally, this PR adds a switch to enable Windows to switch (ie. `cd`) between drives and not just directories on the same drive.

Fix git refs not showing on Windows

---

docbook/docbook-xml/docbook.dtd

DocBook 5.1 and 5.2 allow "Zero or more of" `<refentry>`, whereas DocBook 5.0 and below required "One or more of" `<refentry>`
cf. https://tdg.docbook.org/tdg/5.2/reference

Relax <reference> tag DTD

---

manual.xml.in

This PR replaces the below empty "PHP Manual" [page](https://www.php.net/manual/en/manual.php) with the Preface page that it is linking to.

Remove empty PHP Manual page

---

entities/global.ent

Just happened to stumble across this. All of the external URLs should probably be reviewed.

Fix broken URL to O'Reilly book

---

manual.xml.in

The XForms content will also need to be removed from each of the `doc-$LANG` repos.

Remove XForms from the manual (part of php/doc-en#3579)

---

scripts/qa/extensions.xml.php

Handle extensions state

---

entities/global.ent

The old Website is still HTTP only, but redirects to the new Website; this may not work without issues, though.
Closes GH-153.

Update xmlsoft.org URLs to gitlab.gnome.org

---

manual.xml.in

This is the `doc-base` part of converting the MongoDB extension from a `<set>` to a `<book>` as its top level element. 
Please note that for this PR to work documentation repositories will need to make the same changes as in the accompanying `doc-en` [PR](https://github.com/php/doc-en/pull/3627).

Convert MongoDB from set to book

---

scripts/updateModHistory.php

Add file modification history update script. This script can be used to update the `fileModHistory.php` files in the documentation repos which contain the last modification date/time and the contributor list for every file in the repo.
The ideal way to use this script would be something like a pre-commit hook which would generate the update to the history file, and be merged and potentially reverted together with its parent commit. If anyone knows how to do this on GitHub, please let me know.

Add file modification history update script

---

entities/global.ent

See <https://github.com/php/doc-en/pull/3836>.
---
Likely fails for some translations. Let's see.

Stop bugging Harald

---

manual.xml.in

References should link to faq.installation instead (related to php/doc-en#3785)

Remove the Installation problems chapter

---

docs/contributing.md

Addresses php/web-doc#60 until that changes to use a Markdown engine that automatically creates anchors for headers.

Add anchors for sections of contributing.md

---

scripts/qa/section-order.php

They don't follow the normal rules.

Skip enum definitions in checkSectionErrors()

---

configure.php

This is a quick fix for the newfangled recursive XInclude usage in manual. It runs `xinclude()` in loop for libxml versions < 2.11, and does a few automatic fixups, to avoid breaking all translations at almost any new XInclude usage.
Fix doc-en and almost all languages in my machine. Fails are: doc-tr because it references an xml:id "filter.filters.sanitize" on language-snippets.ent; same on doc-uk. doc-it and doc-ro seems to be effective dead (more than six months without local activity, files several years old)

Recursive XInclude support and some automatix fixups for translations

---

configure.php

This PR better document how XInclude failures are treated on translations. It only cares for `<xi:include>` **without** `<xi:failback>`, so it leaves open `<xi:failback>` usage for other situations.
In fact, I tested this on all languages with `doc-en` stripped of `<xi:failback>`.
As an recommendation, I suggest mass removing all mentions of `<xi:failback>` on `doc-en`, down to XML comments, after 8.4 doc changes calms down, and possibly further creating an github action/trigger that recuses usage of `<xi:failback>`, linking this trigger to mention `XInclude failures are soft errors on translations`. on `configure.php`. The reason being that failed XInclude leaves different artifacts in the presence and absence of `<xi:failback>`. Caring for both is very confusing.

Document and complement XInclude failures as warnings on translations

---

languages.php

This is a small tool I made for creating and maintaining manual language clones. I got tired of searching outside of `doc-base` for listings of languages that builds and publishes, that builds only revcheck, their cloning end points, and so on, to later include/use in other scripts. After a while, it grew into a complete tool for creating and maintaining local language repositories for editors and tool makers.
Current usage:
```
usage: [--clone] [--undo] [--pull] [--mark] [--quiet]
[--list-cvs] [--list-ssv] [--rev] [--all]
[lang] [lang] ...
Options that operates on local repositories:
--clone      Clone a sibling language repo, if not exists
--undo       Restore and clean up repositories to a pristine state
--pull       Executes git pull
--mark       Creates/deletes marking files
--quiet …
```

New tool local language repositories

---

entities/global.ent

The old link is defaulting to the index page.
I found this link to the desired info.

Update URL for Oracle Database DRCP config page

---

configure.php
scripts/genPHP_INI_ENTRY.php

Small cleanup before giving more love to `configure.php`.

Show non default branch in git status

---

configure.php
docs/structure.md

This PR enhances `configure.php` to add XInclude 1.1 partial implementation. That is, XInclude by `xml:id`. Also, it moves the various sections of XInclude functionality into functions, to avoid polluting the global namespace. Points of interest:
* `xinclude_run_byid()`: where the new magic occurs;
* the new code, starting after `if ( $explain )`.
With this PR, would be possible to change manual like this:
```diff
diff --git a/reference/filesystem/functions/fgetcsv.xml b/reference/filesystem/functions/fgetcsv.xml
index 7e1ba4046d..9e313d2630 100644
--- a/reference/filesystem/functions/fgetcsv.xml
+++ b/reference/filesystem/functions/fgetcsv.xml
@@ -62,7 +62,7 @@
</para>
</listitem>
</varlistentry>
-    <varlistentry>
+    <varlistentry xml:id="function.fgetcsv..parameters.separator"> …
```

XInclude by xml:id 

---

configure.php

This PR changes the fix up for `refsect1` to `<title>_</title><simpara>%failed xi:xinclude%</simpara>`. As this cannot be parsed as an XML document, code is also changed to support fix ups that are XML fragments.
This PR, https://github.com/php/doc-it/issues/55 and `doc-en` patch below fixes `doc-it` building.
```diff
diff --git a/reference/gmp/gmp/construct.xml b/reference/gmp/gmp/construct.xml
index df2e9e0893..cdc32f70bb 100644
--- a/reference/gmp/gmp/construct.xml
+++ b/reference/gmp/gmp/construct.xml
@@ -18,9 +18,7 @@
  </refsect1>
 
  <refsect1 role="parameters">
-  <xi:include xpointer="xmlns(db=http://docbook.org/ns/docbook) xpointer(id('function.gmp-init')/db:refsect1[@role='parameters']/*)">
-   <xi:fallback/>
-  </xi:include>
+  <xi:include …
```

XML fragment fixup for `refsect1`

---

scripts/translation/lib/QaFileInfo.php
scripts/translation/lib/RevcheckFileItem.php

fputcsv() escape parameter must be provided as of PHP 8.4. The other preceding parameters are also informed. Named arguments not used for backwards compatibility with PHP < 8.0.
Using `#[\AllowDynamicProperties]` to the class to avoid warnings in PHP 8.2+.

Avoid warnings in PHP 8.4

---

configure.php
languages.php
scripts/file-entities.php

This PR makes `languages.php` more functional on Windows, and also changes repository status to not show ahead/behind of unrelated branches.
As a heads up, also remove a ugly hack for dirs named `PDO` vs `pdo`. If you are on Windows, and start receiving errors of undefined entities that contains `PDO` (upper case), you may need to filesystem remove all files from `en/reference/pdo*`, and then `git restore` then, as git on Windows may not honor case changing moves.

Windows related changes, ahead/behind only current branch

---

configure.php
scripts/file-entities.php

There is nobody building on Windows? Or, there is way to CI test on Windows boxes? I can only borrow a Windows box very rarely to test these things.
On a Win10 machine, this PR fixes:
```
C:\phpdoc>php doc-base\configure.php -q --disable-sources-file --with-lang=de
configure.php on PHP 8.3.14
doc-base: e62034723f03e24728247468043a2c5ffc358a34
en:       f944fb771cf18594fd89f3568f216b4f1a2b7002
de:       d3c11067a19da9059d28b58c8d6f3a9c64a02cf0
Iterating over extension specific version files... OK
Saving it... OK
Modification history file C:\phpdoc/en/fileModHistory.php not found.
Creating empty modification history file...done.
Creating file-entities.ent... done
Loading and parsing manual.xml... failed.
[error file:/C:/phpdoc/doc-base/temp/manual.conf 2:74] Invalid URI: …
```

Fix Windows build (forward slashes everywhere)

---

configure.php
docs/structure.md

Make text more detailed and explicit, and also document what `configure.php` does in case of `xml:id` duplications.

Document xml:id usage

---

scripts/file-entities.php

This PR partially reverts https://github.com/php/doc-base/pull/213 , re-enabling the creation of separated files for directory file-entities.
Per documentation, [LIBXML_PARSEHUGE](https://www.php.net/manual/en/libxml.constants.php#constant.libxml-parsehuge):
> Sets XML_PARSE_HUGE flag, which relaxes any hardcoded limit from the parser. This affects limits like maximum depth of a document or the entity recursion, as well as limits of the size of text nodes.
Even being a very old option (since libxml 2.7.0 / PHP 5.3 eras), it is insufficient for PHP manual building, in some OS and libxml versions. Until there is something like a truly `LIBXML_PARSEUNLIMITED`, PHP Manuals will soon become unparseable.

Create separated files for directory file-entities

---

scripts/translation/libqa/OutputBuffer.php
scripts/translation/libqa/SyncFileList.php
scripts/translation/libqa/XmlFrag.php
scripts/translation/qaxml-sync-attributes.php
scripts/translation/qaxml-sync-entities.php

This tool check for XML entity usage between doc-en and translations. This is particularly important in the case of file-entities, where mismatchs almost always cause build failures.

Command line tool for XML sync testing between languages: entities

---

configure.php

An effective fix for https://github.com/php/doc-base/issues/224. Will generate around or less than 10 warnings in almost all translations, where XInclude failures are "erasing" parts of manual translations.

Warn/show failed XIncludes

---

scripts/translation/README.md
scripts/translation/lib/OutputIgnoreArgv.php
scripts/translation/lib/OutputIgnoreBuffer.php
scripts/translation/lib/RevcheckData.php
scripts/translation/lib/RevcheckFileList.php
scripts/translation/lib/RevtagParser.php
scripts/translation/lib/XmlUtil.php
scripts/translation/libqa/ArgvParser.php
scripts/translation/libqa/OutputBuffer.php
scripts/translation/libqa/OutputIgnore.php
scripts/translation/libqa/XmlFrag.php
scripts/translation/qaxml-attributes.php
scripts/translation/qaxml-entities.php
scripts/translation/qaxml-pi.php
scripts/translation/qaxml-revtag.php
scripts/translation/qaxml-tags.php
scripts/translation/qaxml-ws.php
scripts/translation/qaxml.a.php
scripts/translation/qaxml.e.php
scripts/translation/qaxml.p.php
scripts/translation/qaxml.t.php

This PR rewrites the last of old qaxml tools into something that is almost independent of "lib revcheck" code, and adapted to be run in all translations.
After this PR is merged, and new tools announced, the old tools/code removing will be possible. The only dependence renaming are `/lib/RevtagParser.php`, that is a isolated file, and `SyncFileList` calling into `RevcheckRun`, that can be replaced with a simple `.xml` listing, as the new tools now inspect all files, and does not filter for `TranslatedOk` anymore.

Command line tools for XML sync testing between languages

---

scripts/translation/libqa/SyncFileList.php

Uses `RevcheckFileList` instead of `RevcheckRun` for way faster file listing, that avoids calculating revcheck status and contents loading, that is not necessary for the new qaxml tools.

Faster file listing

---

configure.php

`DOMDocument->xinclude()` returns negative numbers on partial executions, meaning that this return cannot be used for counting or stopping conditions on loops.
The old code sometimes reports errors of previous runs, also fixed.
The function `xinclude_debug_report()` can probably be removed, as the new warning reporting on failed XInclude now duplicated the errors, and is less expressive.

Workarounds for DOMDocument->xinclude() return

---

scripts/translation/libqa/OutputBuffer.php
scripts/translation/libqa/OutputIgnore.php
scripts/translation/qaxml-tags.php

Fix cases where different arguments would generate add/del ignore for the same ignore hashes.
Also fixes unstable ignores of `scripts/translation/qaxml-tags.php`, that have multi-stage output and ignores.

Fix unstable add/del ignores

---

configure.php

This PR move all generation of PhD specific files to the end of `configure.php`, in particular, to after `manual.xml` validation, so the "time to validate" and "time to error" is vastly reduced on machines without SSD.
Also, this empathizes that these generated files are not relevant for `manual.xml` validation or generation, and so testing can concentrate on these functions alone.
Unrelated, but... time to remove the mention of `nice` in final messages?

PhD stuff at end of `configure.php`

---

configure.php
scripts/broken.php

This is a PR that increments warnings in almost all translations, so I ask for comments for a longer time, before commiting.
With this PR, when a `configure.php` fails on the first XML loading, it will run `scripts/broken.php`, to help debug issues that are present in one individual file.
This PR **also** will run `scripts/broken.php` as the last step of a *successful* `configure.php` run, to report "invisible" issues that may be accumulating, even if the language manual builds and validates.
The warnings are:
* `Error: Opening and ending tag mismatch:`: Yes, there are XML files that are just plain broken, in some repositories.
* `Error: Start tag expected, '<' not found`: These are mostly files named `entities.foo.bar.xml`. They are auto generated, and should not exist in translations. …

Post check individual XML files for know issues

---

docs/local-setup.md
languages.php

`doc-ro` appears to be abandoned, and is marked inactive on https://www.php.net/manual/help-translate.php .
Also, document usage of `git` `core-autocrlf` option to avoid future `\r\n` files on document repositories.
Aside, the link for Polish SVN archive on link above is broken, because `http://docs.php.net/manual/pl` does not exist.
These are minor changes, and I plan to merge it on few weeks. I would like comments (and testing) if the suggested solution for Windows users.

Disable doc-ro in languages.php and document core.autocrlf usage

---

entities/global.ent

For php/doc-en#4875
In preparation for revisions to the PCRE Extension reference chapter in an associated PR over in the `doc-en` repoistory.
The older URLs are mostly for the PCRE1 library which isn't applicable since PHP 7.3.0.

Add PCRE2 related URLs to global.ent
