entities/global.ent
To be used in `DatePeriod::__construct()`
See [#613](https://github.com/php/doc-en/pull/613)
=> Add new entity for repeating intervals

scripts/qa/section-order.php
This QA scripts checks if all mandatory sections are present and that they are in the correct order, if not print the file name.
The docs stills needs fixing and the script possibly improved before we can run this in CI for doc-en.
Also just to check, @thinkverse you're fine with relicensing your code under the PHP License and merge it into the project?
=> Add section order QA script

entities/global.ent, scripts/qa/entities.php
These are unused across all our current translations, also improve the script slightly to provide more accurate information.
=> Remove unused global entities

entities/global.ent
close https://github.com/php/doc-en/issues/763
=> Fix broken link

manual.xml.in
Doc base changes for https://github.com/php/doc-en/pull/612
=> Remove FrontbaseSQL docs

scripts/docgen/docgen.php
And trim trailing whitespace
Mentioned in https://github.com/php/doc-en/pull/885#discussion_r697786840
=> Generate `<type>int</type>` instead of `integer`

manual.xml.in
See https://github.com/php/doc-en/pull/885
=> Add var_representation link to "Other Basic Extensions"

manual.xml.in
For https://github.com/php/doc-en/pull/941
=> Add PHP 8.0 to 8.1 migration guide

manual.xml.in
relates to https://github.com/php/doc-en/pull/1172
=> Added link language.fibers from manual toppage.

entities/global.ent
Required for https://github.com/php/doc-en/pull/1016
=> Add link to sqlsrv Linux instructions

entities/global.ent
http://sourcefrog.net/projects/natsort/ says it moved to GH, which is also slightly easier on the eyes 👍🏻
=> Update natural sort algo URL

scripts/qa/check-examples.php
This really should do some XML parsing instead of regex guess work, but I did find a bunch of errors with it.
=> Refactor the Check Example QA script

manual.xml.in
See https://github.com/tpunt/pht/issues/11
=> Remove PHT from docs

entities/global.ent
See https://github.com/php/doc-en/pull/1667 and https://github.com/php/web-php/pull/595
=> Remove url.crypt.blowfish entity

manual.xml.in
Related to https://github.com/php/doc-en/pull/1900
=> Add simdjson pecl to the list to generate

manual.xml.in
=> Add ext/random to manual.xml.in

entities/global.ent
=> Add URLs for random engine specifications to global.ent

manual.xml.in
Needed for https://github.com/php/doc-en/pull/1990
=> Add predefined attributes section

entities/acronyms.xml
(Disjoint -> Disjunctive)  Normal Form
See https://wiki.php.net/rfc/dnf_types and https://en.wikipedia.org/wiki/Disjunctive_normal_form
=> Fixed DNF in acronyms.xml

scripts/qa/section-order.php
This should fix the build errors (https://github.com/php/doc-en/actions/runs/3435904337/jobs/5728812362#step:5:6) of https://github.com/php/doc-en/pull/1983
=> Fix constructorsynopsis and destructorsynopsis validation

entities/global.ent
Fix https://github.com/php/doc-en/issues/2457
=> Fix broken link for setlocale

entities/global.ent
Required for https://github.com/php/doc-en/pull/1966.
=> Add OpenSSL config(5) URL

entities/acronyms.xml
Follow-up of https://github.com/php/doc-base/pull/95#pullrequestreview-1569722973
=> Add PKCS and CSR acronyms

scripts/revcheck.php
This PR does a bit of cleanup, before adding the main functionality: a new "Days" column to indicate how many days passed since the last update on `en/`.
The new column:
Sending this PR from another repo because the initial fork contains several other alterations.
=> Add 'Days' column and cleanups

configure.php
This makes XInclude/XPointer error reporting less annoying, but doesn't omit them totally.
Impacts https://github.com/php/doc-base/pull/80 and https://github.com/php/doc-base/pull/85, end avoids the massive https://github.com/php/doc-en/pull/2015.
For https://github.com/php/doc-base/pull/85, I propose making the build fail only on `en/`, as making this a error on translations would kill (almost) them all.
=> Simplify XInclude/XPointer error reporting.

manual.xml.in
relates to: https://github.com/php/doc-en/pull/2780
=> added PHP 8.3 migration guide link

scripts/qa/section-order.php
See https://github.com/php/doc-en/pull/2813
=> Skip ext/dom pages that rely on xincludes

configure.php, scripts/aspell.php, scripts/build-chms-config.php, scripts/build-chms-history.php, scripts/build-chms.php, scripts/check-trans-maint.php, scripts/check-trans-params.php, scripts/check-trans.php, scripts/check_phpdoc/build.php, scripts/check_phpdoc/view_check_phpdoc.php, scripts/dbtags.php, scripts/docgen/docgen.php, scripts/file-entities.php.in, scripts/genPHP_INI_ENTRY.php, scripts/grep-files.php, scripts/include/FileData.class.php, scripts/include/lib-translations.inc.php, scripts/missing-entities.php.in, scripts/notes_extract.php, scripts/notes_stats.php, scripts/orphan_notes.php, scripts/process.php, scripts/revcheck.php, scripts/script-skel.php, scripts/spell-checker.php, scripts/test_missing-entities.php.in, scripts/versions.php, scripts/xml-check.php
=> Update licenses to PHP 3.01

scripts/qa/check-acronyms.php, scripts/qa/check-examples.php, scripts/qa/check-valid-function.php, scripts/qa/checkent.php, scripts/qa/entities.php, scripts/qa/entity-usage.php, scripts/qa/extensions.xml.php, scripts/qa/section-order.php
Also drive by fix of my name
Sorry @ramsey I forgot those when doing the other PR.
=> Update QA script licenses to PHP 3.01

entities/global.ent
close https://github.com/php/doc-en/pull/3041
=> Fix MongoDB links in the library tutorial page

entities/global.ent
See https://github.com/php/php-src/issues/13517
=> Update expat library URLs

entities/global.ent
=> Update ML subscribe/unsubscribe

configure.php
Copy the file modification history file from the language repository or create an empty one. This file will be used to add last commit date/time and author, as well as a list of all contributors to the documentation pages.
=> Add file modification history setup

configure.php
Define GLOB_BRACE if it is [not defined](https://www.php.net/manual/en/filesystem.constants.php#constant.lock-nb). 
Fix typo in directory path string.
An alternative to #39.
=> Define GLOB_BRACE if it is not defined

entities/global.ent
=> Update URLs for PDO Informix

entities/global.ent
Alphabetize the url section
Add entry for Visual C Redistributable for use in php docs repository @ https://github.com/php/doc-en/pull/3613/
=> Update global.ent (alphabetical + entry)

entities/acronyms.xml, entities/global.ent
=> Define acronyms and add URL related to hash functions

entities/global.ent
Adding URLs needed in https://github.com/php/doc-en/pull/3639
=> mariadb percona tidb

entities/global.ent
Needed by https://github.com/php/doc-en/pull/3763
=> Add entities for Unix source install instructions

entities/global.ent
The original RST specs were recently ported to Markdown
=> Update URLs for MongoDB specs

entities/global.ent
This PR add an URL for Win32Service documentation.
See https://github.com/php/doc-en/pull/3871
=> Add entity url for Win32Service

docs/style.md
Based on php/web-doc#33 by @tiffany-taylor
=> Add style guideline about conditional conjunction formatting

docs/cs-for-examples.md
Doesn't seem to be any pushback on updating this, so let's do it
=> Update to PER CS coding style instead of PEAR

scripts/docgen/book.developer.tpl, scripts/docgen/book.tpl, scripts/docgen/class.tpl, scripts/docgen/constructor.tpl, scripts/docgen/docgen.php, scripts/docgen/function.tpl, scripts/docgen/ini.tpl, scripts/docgen/mapping.tpl, scripts/docgen/method.tpl, scripts/docgen/setup.tpl, skeletons/book.xml, skeletons/classname.xml, skeletons/configure.xml, skeletons/constants.xml, skeletons/examples.xml, skeletons/exceptionname.xml, skeletons/function.xml, skeletons/ini.xml, skeletons/method.xml, skeletons/reference.xml, skeletons/setup.xml, skeletons/versions.xml
Doc gen is generating outdated markup already, especially for classes.
=> Update templates for documentation pages

docbook/JING_LICENSE
See: https://github.com/php/doc-en/issues/3912#issuecomment-2523399759
=> Include Jing license that I forgot to add when commiting the JAR

manual.xml.in
For https://github.com/php/doc-en/pull/4320
=> add Xpass extension

configure.php
=> Unsupport trunk/

entities/acronyms.xml, scripts/docgen/docgen.php, scripts/gen-phpdoc-tz-list.php, scripts/genPHP_INI_ENTRY.php
=> Remove $Revision$

entities/global.ent, manual.xml
To be committed with https://github.com/php/doc-en/pull/4850
=> Add TOC entry and links for PIE introduction
